# First stage: Build the Maven project
FROM maven:3.8.2-jdk-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Second stage: Run the Spring Boot application
FROM openjdk:11-jdk-slim
WORKDIR /app
COPY --from=build /app/target/EduLearnBackendApplication-0.0.1-SNAPSHOT.jar EduLearnBackendApplication.jar
CMD ["java", "-jar", "EduLearnBackendApplication.jar"]
